import { nanoid } from "nanoid";
import type { CVData } from "./schema";

export const SAMPLE_CV: CVData = {
  personal: {
    firstName: "Marta",
    lastName: "Nowak",
    role: "Senior UX Designer",
    photo: "",
    address: "ul. Marszałkowska 84, 00-514 Warszawa",
    email: "marta.nowak@agentcv.pl",
    website: "martanowak.design",
    phone: "+48 512 903 447",
  },
  profile:
    "Projektantka UX z 8-letnim doświadczeniem w produktach B2B i fintech. Prowadziłam redesign aplikacji bankowości mobilnej, który zwiększył retencję o 28% w 6 miesięcy. Specjalizuję się w design systemach, badaniach jakościowych i warsztatach odkrywania produktu.",
  education: [
    {
      id: "edu-1",
      school: "ASP w Warszawie",
      startYear: "2014",
      endYear: "2017",
      degree: "Magister, Wzornictwo (Design Interakcji)",
      location: "Warszawa",
      startMonth: "",
      endMonth: "",
      current: false,
    },
    {
      id: "edu-2",
      school: "SWPS Uniwersytet",
      startYear: "2011",
      endYear: "2014",
      degree: "Licencjat, Psychologia społeczna",
      location: "Warszawa",
      startMonth: "",
      endMonth: "",
      current: false,
    },
  ],
  skills: {
    professional: [
      "Figma",
      "Design Tokens",
      "Badania UX",
      "Warsztaty odkrywania",
      "Prototypowanie",
      "Storybook",
    ],
    personal: [
      "Komunikacja",
      "Praca w zespole",
      "Zarządzanie czasem",
      "Krytyczne myślenie",
      "Uważne słuchanie",
    ],
  },
  employment: [
    {
      id: "emp-1",
      position: "Senior UX Designer",
      company: "BankoweFinTech S.A.",
      location: "Warszawa",
      startYear: "2022",
      startMonth: "",
      endYear: "",
      endMonth: "",
      current: true,
      description:
        "Prowadzę redesign aplikacji mobilnej dla 1,2 mln użytkowników. Wprowadziłam design system oparty na tokenach, który skrócił czas developmentu nowych ekranów o 40%. Koordynuję zespół 4 projektantów i współpracuję z 3 zespołami produktowymi.",
    },
    {
      id: "emp-2",
      position: "Product Designer",
      company: "SaaS Logistics Sp. z o.o.",
      location: "Warszawa",
      startYear: "2019",
      startMonth: "",
      endYear: "2022",
      endMonth: "",
      current: false,
      description:
        "Projektowałam dashboardy dla firm logistycznych (30+ klientów B2B). Zmniejszyłam liczbę zgłoszeń do supportu o 35% dzięki przebudowie flow zakładania przesyłki. Współtworzyłam bibliotekę komponentów używaną przez 8 produktów.",
    },
    {
      id: "emp-3",
      position: "UX Designer",
      company: "AgencjaInteraktywna.pl",
      location: "Kraków",
      startYear: "2017",
      startMonth: "",
      endYear: "2019",
      endMonth: "",
      current: false,
      description:
        "Projektowałam serwisy e-commerce (12 wdrożeń) dla klientów retail i FMCG. Prowadziłam testy użyteczności z użytkownikami końcowymi i warsztaty z product ownerami.",
    },
  ],
  languages: [
    { id: "lang-1", name: "Polski", level: "native" },
    { id: "lang-2", name: "Angielski", level: "C1" },
    { id: "lang-3", name: "Niemiecki", level: "B1" },
  ],
  projects: [
    {
      id: "proj-1",
      name: "Design System Orbit",
      description:
        "Open-source design system dla fintech — 120 komponentów, tokens w OKLCH, pełna dokumentacja w Storybook. 4,2k gwiazdek na GitHub.",
      url: "github.com/orbit-ds",
    },
    {
      id: "proj-2",
      name: "Badanie rynku kart płatniczych 2024",
      description:
        "Raport z wywiadów z 32 użytkownikami kart wielowalutowych. Wnioski wdrożone w aplikacji mBank i PKO BP.",
      url: "",
    },
  ],
  certifications: [],
  volunteer: [],
  publications: [],
  awards: [],
  conferences: [],
  hobbies: [],
  references: [],
  customSections: [],
  rodo: {
    type: "standard",
    companyName: "",
  },
  settings: {
    templateId: "orbit",
    fontFamily: "manrope",
    fontSize: 10,
    photoShape: "circle",
    showProfile: true,
    showEducation: true,
    showEmployment: true,
    showSkills: true,
    showLanguages: false,
    showProjects: false,
    showCertifications: false,
    showVolunteer: false,
    showPublications: false,
    showAwards: false,
    showConferences: false,
    showHobbies: false,
    showReferences: false,
    showLinks: true,
    hiddenContactFields: [],
  },
};

export function createEmptyCV(): CVData {
  return {
    personal: {
      firstName: "",
      lastName: "",
      role: "",
      photo: "",
      address: "",
      email: "",
      website: "",
      phone: "",
    },
    profile: "",
    education: [
      {
        id: `edu-${nanoid(6)}`,
        school: "",
        degree: "",
        location: "",
        startYear: "",
        startMonth: "",
        endYear: "",
        endMonth: "",
        current: false,
      },
    ],
    skills: { professional: [], personal: [] },
    employment: [
      {
        id: `emp-${nanoid(6)}`,
        position: "",
        company: "",
        location: "",
        startYear: "",
        startMonth: "",
        endYear: "",
        endMonth: "",
        current: false,
        description: "",
      },
    ],
    languages: [],
    projects: [],
    certifications: [],
    volunteer: [],
    publications: [],
    awards: [],
    conferences: [],
    hobbies: [],
    references: [],
    customSections: [],
    rodo: { type: "standard", companyName: "" },
    settings: {
      templateId: "orbit",
      fontFamily: "manrope",
      fontSize: 10,
      photoShape: "circle",
      showProfile: true,
      showEducation: true,
      showEmployment: true,
      showSkills: true,
      showLanguages: false,
      showProjects: false,
      showCertifications: false,
      showVolunteer: false,
      showPublications: false,
      showAwards: false,
      showConferences: false,
      showHobbies: false,
      showReferences: false,
      showLinks: true,
      hiddenContactFields: [],
    },
  };
}
