export const INDUSTRIES = [
  { value: "it", label: "IT / Programowanie" },
  { value: "data", label: "Data / Analityka / ML" },
  { value: "logistics", label: "Logistyka / Magazyn / Spedycja" },
  { value: "production", label: "Produkcja / Przemysł / CNC" },
  { value: "retail", label: "Handel / Sprzedaż detaliczna" },
  { value: "ecommerce", label: "E-commerce / Sprzedaż online" },
  { value: "automotive", label: "Motoryzacja / Serwis samochodowy" },
  { value: "construction", label: "Budownictwo / Instalacje" },
  { value: "engineering", label: "Inżynieria / Konstrukcja" },
  { value: "gastro", label: "Gastronomia / Hotelarstwo" },
  { value: "transport", label: "Transport / Kierowcy" },
  { value: "healthcare", label: "Opieka zdrowotna / Farmacja" },
  { value: "finance", label: "Finanse / Bankowość" },
  { value: "accounting", label: "Księgowość / Podatki" },
  { value: "insurance", label: "Ubezpieczenia" },
  { value: "marketing", label: "Marketing / Reklama / PR" },
  { value: "hr", label: "HR / Kadry / Płace" },
  { value: "education", label: "Edukacja / Szkolenia" },
  { value: "media", label: "Media / Dziennikarstwo" },
  { value: "legal", label: "Prawo / Administracja publiczna" },
  { value: "design", label: "Design / Grafika / UX" },
  { value: "energy", label: "Energetyka / OZE" },
  { value: "telecom", label: "Telekomunikacja / Cyberbezpieczeństwo" },
  { value: "beauty", label: "Uroda / Fryzjerstwo / Kosmetyka" },
  { value: "agriculture", label: "Rolnictwo / Leśnictwo" },
  { value: "security", label: "Ochrona / Bezpieczeństwo fizyczne" },
  { value: "other", label: "Inna branża" },
] as const;

export type IndustryValue = (typeof INDUSTRIES)[number]["value"];
