/**
 * Pracuś AI Knowledge Base
 *
 * Structured data from:
 * - ESCO (European Skills, Competences, Qualifications and Occupations)
 * - O*NET (Occupational Information Network)
 * - Barometr Zawodów 2025 (Polish Occupation Barometer)
 * - PRK / ZSK (Polish Qualifications Framework, 8 levels)
 * - BKL PARP (Human Capital Balance, 17 industries)
 * - PSZ Praca (Polish Public Employment Service, KZiS classification)
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export interface IndustryProfile {
  id: string;
  label: string;
  escoGroup: string;
  onetZone: 1 | 2 | 3 | 4 | 5;
  deficit: "deficytowy" | "zrównoważony" | "nadwyżkowy";
  topRoles: string[];
  coreSkills: string[];
  actionVerbs: string[];
  achievementTemplates: string[];
  certifications: string[];
  atsKeywords: string[];
  toneHint: string;
}

// ─── Industry Profiles ────────────────────────────────────────────────────────

export const INDUSTRY_PROFILES: Record<string, IndustryProfile> = {
  logistics: {
    id: "logistics",
    label: "Logistyka / Magazyn / Spedycja",
    escoGroup: "ESCO 9.3 — Transport and storage workers",
    onetZone: 2,
    deficit: "deficytowy",
    topRoles: ["Magazynier", "Operator wózka widłowego", "Koordynator logistyki", "Specjalista ds. spedycji", "Kierownik zmiany", "Planista produkcji", "Pracownik kompletacji"],
    coreSkills: ["Obsługa wózka widłowego", "System WMS (SAP EWM, Comarch)", "Dokumentacja CMR/WZ/PZ", "Inwentaryzacja", "Zarządzanie zespołem zmianowym", "BHP magazynowe", "Obsługa skanerów kodów", "Lean / 5S / Kaizen", "Excel (tabele przestawne)", "Prace na wysokości"],
    actionVerbs: ["koordynowałem", "kompletowałem", "inwentaryzowałem", "załadowałem", "zoptymalizowałem", "nadzorowałem", "szkoliłem", "wdrożyłem", "rozładowałem", "raportowałem"],
    achievementTemplates: [
      "Koordynowałem pracę zespołu [X] osób na zmianie [nocnej/dziennej], odpowiadając za KPI wydajności",
      "Wdrożyłem procedurę [X], która obniżyła liczbę [błędnych wysyłek/uszkodzeń] o [X]% w ciągu [X] miesięcy",
      "Obsługa systemu WMS [nazwa], kompletacja [X] zamówień/zmianę z dokładnością [X]%",
      "Przeprowadziłem inwentaryzację [X] pozycji SKU, średnia dokładność >[X]%",
      "Szkoliłem nowych pracowników — przeszkoliłem [X] osób w [roku]",
    ],
    certifications: ["Uprawnienia UDT na wózki widłowe (czołowe, boczne, wysokiego składowania)", "Szkolenie BHP (obsługa magazynu)", "Prawo jazdy kat. B/C", "Certyfikat operatora suwnicy", "Kurs pierwszej pomocy"],
    atsKeywords: ["WMS", "SAP EWM", "UDT", "wózek widłowy", "kompletacja", "inwentaryzacja", "CMR", "5S", "Lean", "BHP", "picking", "packing", "FIFO", "LIFO", "cross-docking"],
    toneHint: "Pisz konkretnie: maszyny, systemy, liczby sztuk, tony, palety. Recruiter w logistyce szuka certyfikatów i doświadczenia zmianowego.",
  },

  production: {
    id: "production",
    label: "Produkcja / Przemysł",
    escoGroup: "ESCO 7 — Craft and related trades workers / ESCO 8 — Plant and machine operators",
    onetZone: 2,
    deficit: "deficytowy",
    topRoles: ["Operator CNC", "Spawacz", "Monter", "Tokarz", "Frezer", "Ślusarz", "Operator linii produkcyjnej", "Kontroler jakości"],
    coreSkills: ["Obsługa maszyn CNC (Mazak, Fanuc, Haas, DMG Mori)", "Spawanie MIG/MAG/TIG", "Czytanie rysunku technicznego", "Pomiary (suwmiarka, mikrometr, CMM)", "Kontrola jakości (SPC, ISO 9001)", "Obsługa tokarki/frezarki konwencjonalnej", "Programowanie G-code", "Lean Manufacturing / TPM / SMED"],
    actionVerbs: ["obsługiwałem", "produkowałem", "spawałem", "montowałem", "toczyłem", "frezowałem", "kontrolowałem", "kalibrowałem", "naprawiałem", "programowałem"],
    achievementTemplates: [
      "Obsługiwałem [maszynę] [producent], produkując [X] części/zmianę z dokładnością ±[X]mm",
      "Spawałem konstrukcje [typ] metodą [MIG/MAG/TIG] zgodnie z normą [EN ISO 9606-1]",
      "Zredukowałem czas przezbrojenia z [X] do [X] min (metoda SMED), zwiększając OEE o [X]%",
      "Wykonywałem pomiary kontrolne (suwmiarka, mikrometr, CMM) z tolerancją [X]",
      "Utrzymywałem wskaźnik braków poniżej [X]% przy produkcji seryjnej [X] szt/miesiąc",
    ],
    certifications: ["EN ISO 9606-1 (spawanie)", "Uprawnienia UDT (suwnice, wózki)", "Kurs obsługi CNC", "Certyfikat kontroli jakości ISO 9001", "Szkolenie SEP (grupa 1, 2 lub 3)", "Uprawnienia do obsługi pras hydraulicznych"],
    atsKeywords: ["CNC", "MIG/MAG", "TIG", "ISO 9606", "rysunek techniczny", "tolerancja", "suwmiarka", "SPC", "OEE", "5S", "Kaizen", "SMED", "TPM", "G-code", "Fanuc", "Mazak"],
    toneHint: "Podawaj konkretne maszyny (producent + model), metody spawania, normy ISO. Recruiter w produkcji szuka uprawnień i znajomości maszyn.",
  },

  retail: {
    id: "retail",
    label: "Handel / Sprzedaż detaliczna",
    escoGroup: "ESCO 5.2 — Sales workers",
    onetZone: 2,
    deficit: "zrównoważony",
    topRoles: ["Kasjer", "Sprzedawca", "Kierownik zmiany", "Merchandiser", "Kierownik sklepu", "Doradca klienta", "Pracownik sali sprzedaży"],
    coreSkills: ["Obsługa kasy fiskalnej", "Obsługa terminala płatniczego", "Obsługa kasy samoobsługowej (SCO)", "Ekspozycja towaru (planogram)", "Inwentaryzacja", "Obsługa reklamacji", "Raportowanie sprzedaży", "Zarządzanie zespołem sklepu"],
    actionVerbs: ["obsługiwałem", "sprzedawałem", "doradzałem", "zarządzałem", "ekspediowałem", "rozpatrywałem", "szkoliłem", "realizowałem", "raportowałem", "promowałem"],
    achievementTemplates: [
      "Obsługiwałem średnio [X] klientów dziennie, utrzymując ocenę satysfakcji [X]/5",
      "Zarządzałem zespołem [X] osób, realizując plan sprzedaży na poziomie [X]%",
      "Wdrożyłem nowy układ ekspozycji, który zwiększył sprzedaż kategorii [X] o [X]%",
      "Prowadziłem inwentaryzację [X] pozycji asortymentowych z dokładnością [X]%",
      "Awansowałem z [stanowisko] na [stanowisko] w ciągu [X] miesięcy",
    ],
    certifications: ["Szkolenie z obsługi kasy fiskalnej", "HACCP (dla sklepów spożywczych)", "Kurs obsługi wózka paletowego", "Szkolenie BHP", "Certyfikat merchandisera"],
    atsKeywords: ["kasa fiskalna", "SCO", "planogram", "merchandising", "KPI sprzedaży", "inwentaryzacja", "obsługa klienta", "reklamacja", "HACCP", "raportowanie"],
    toneHint: "Podkreślaj ilość obsłużonych klientów/dzień, realizację planów %, zarządzanie zespołem. Recruitera interesuje czy umiesz liczyć i sprzedawać.",
  },

  automotive: {
    id: "automotive",
    label: "Motoryzacja / Serwis samochodowy",
    escoGroup: "ESCO 7.2 — Metal, machinery and related trades workers",
    onetZone: 3,
    deficit: "deficytowy",
    topRoles: ["Mechanik samochodowy", "Mechanik pojazdowy", "Elektromechanik", "Diagnosta", "Lakiernik", "Blacharz", "Serwisant"],
    coreSkills: ["Diagnostyka komputerowa (OBD2, ISTA, ODIS, VAS)", "Naprawa silników benzynowych i diesel", "Serwis aut hybrydowych i elektrycznych", "Wymiana i regeneracja skrzyń biegów (manualne, DSG, automatyczne)", "Obsługa klimatyzacji (R134a, R1234yf)", "Geometria kół (Hunter, Beissbarth)", "Spawanie (MIG, gazowe)", "Lakierowanie natryskowe"],
    actionVerbs: ["naprawiałem", "diagnozowałem", "serwisowałem", "wymieniałem", "regenerowałem", "kalibrowałem", "montowałem", "lakierowałem", "spawałem", "regulowałem"],
    achievementTemplates: [
      "Diagnozowałem i naprawiałem [X] pojazdów miesięcznie ([marki]), średni czas naprawy [X]h",
      "Specjalizowałem się w [hybrydy/elektryki/diesel], obsługując systemy [nazwa]",
      "Serwisowałem klimatyzację samochodową (R1234yf), wykonując [X] napełnień/miesiąc",
      "Prowadziłem przeglądy rejestracyjne jako diagnosta, badając [X] pojazdów/dzień",
      "Wymieniłem i regenerowałem [X] skrzyń biegów [typ] w ciągu [X] lat",
    ],
    certifications: ["Uprawnienia diagnosty samochodowego", "Certyfikat obsługi klimatyzacji (F-gaz)", "Uprawnienia SEP (grupa 1 — elektryka pojazdowa)", "Prawo jazdy kat. B", "Szkolenie z obsługi aut hybrydowych/elektrycznych"],
    atsKeywords: ["OBD2", "diagnostyka komputerowa", "DSG", "hybryda", "elektryk", "klimatyzacja", "geometria kół", "przegląd rejestracyjny", "F-gaz", "ISTA", "ODIS"],
    toneHint: "Podawaj marki aut, nazwy systemów diagnostycznych, typy napraw. Warsztat szuka kogoś kto zna konkretne marki i technologie.",
  },

  construction: {
    id: "construction",
    label: "Budownictwo / Instalacje",
    escoGroup: "ESCO 7.1 — Building and related trades workers",
    onetZone: 2,
    deficit: "deficytowy",
    topRoles: ["Murarz", "Elektryk", "Hydraulik", "Monter instalacji", "Tynkarz", "Płytkarz", "Cieśla", "Operator koparki"],
    coreSkills: ["Instalacje elektryczne (nn, SN)", "Instalacje wod-kan i CO", "Montaż instalacji sanitarnych", "Czytanie schematów elektrycznych", "Obsługa koparki/ładowarki", "Tynkowanie maszynowe", "Układanie glazury i terakoty", "Prace na wysokości (rusztowania)"],
    actionVerbs: ["montowałem", "instalowałem", "murowałem", "tynkowałem", "układałem", "podłączałem", "wykonywałem", "remontowałem", "nadzorowałem", "projektowałem"],
    achievementTemplates: [
      "Wykonałem instalację elektryczną w [X] budynkach [typ] o łącznej powierzchni [X] m²",
      "Montowałem instalacje wod-kan i CO w [X] lokalach [mieszkalnych/biurowych]",
      "Nadzorowałem brygadę [X] osób na budowie [typ obiektu] o wartości [X] mln PLN",
      "Wykonałem [X] m² tynków maszynowych/płytek/posadzek w terminie [X] tygodni",
      "Obsługiwałem [koparko-ładowarkę/dźwig] przy inwestycjach [typ]",
    ],
    certifications: ["Uprawnienia SEP (grupa 1 — do 1kV)", "Uprawnienia UDT (koparki, dźwigi)", "Szkolenie pracy na wysokości", "Uprawnienia spawalnicze", "Certyfikat operatora koparki (klasa III)"],
    atsKeywords: ["SEP", "instalacja elektryczna", "wod-kan", "CO", "rusztowanie", "tynk maszynowy", "glazura", "hydraulik", "montaż", "budowa"],
    toneHint: "Podawaj m² wykonanej pracy, liczbę budynków, wartość inwestycji. Budownictwo = twarde dane i uprawnienia.",
  },

  it: {
    id: "it",
    label: "IT / Programowanie",
    escoGroup: "ESCO 2.5 — ICT professionals",
    onetZone: 4,
    deficit: "deficytowy",
    topRoles: ["Frontend Developer", "Backend Developer", "Full Stack Developer", "DevOps Engineer", "Data Engineer", "QA Engineer", "Product Manager", "Scrum Master"],
    coreSkills: ["JavaScript/TypeScript", "React/Next.js/Vue", "Python/Java/Go", "SQL/NoSQL (PostgreSQL, MongoDB)", "Git/GitHub/GitLab", "Docker/Kubernetes", "CI/CD (GitHub Actions, Jenkins)", "Cloud (AWS, GCP, Azure)", "REST API / GraphQL", "Agile/Scrum"],
    actionVerbs: ["wdrożyłem", "zaprojektowałem", "zoptymalizowałem", "zautomatyzowałem", "zintegrowałem", "zrefaktoryzowałem", "zdeployowałem", "przetestowałem", "zarchitekturowałem", "zmigrowałem"],
    achievementTemplates: [
      "Wdrożyłem [system/feature] obsługujący [X] użytkowników dziennie, redukując czas odpowiedzi o [X]%",
      "Zaprojektowałem architekturę [mikroserwisów/monolitu] obsługującą [X] req/s",
      "Zoptymalizowałem [zapytania SQL/bundel JS/czas buildu] z [X] do [X] ([X]% poprawa)",
      "Prowadzę zespół [X] developerów, code review [X] PR/tydzień",
      "Zautomatyzowałem [CI/CD/testy/deploy], skracając czas release z [X] do [X]",
    ],
    certifications: ["AWS Certified Solutions Architect", "Google Cloud Professional", "Scrum Master (PSM I/II)", "ISTQB Foundation", "Kubernetes CKA/CKAD"],
    atsKeywords: ["React", "TypeScript", "Node.js", "Python", "Docker", "Kubernetes", "AWS", "CI/CD", "REST API", "microservices", "Agile", "Scrum", "Git"],
    toneHint: "Podawaj technologie, stack, skale (użytkownicy, req/s, dane). IT recruiter skanuje CV pod kątem tech stacku — musisz go mieć na wierzchu.",
  },

  gastro: {
    id: "gastro",
    label: "Gastronomia / Hotelarstwo",
    escoGroup: "ESCO 5.1 — Personal service workers / ESCO 9.4 — Food preparation",
    onetZone: 2,
    deficit: "deficytowy",
    topRoles: ["Kucharz", "Kelner", "Barista", "Cukiernik", "Szef kuchni", "Recepcjonista hotelowy", "Barman", "Pomoc kuchenna"],
    coreSkills: ["Przygotowywanie dań (kuchnia polska, włoska, azjatycka)", "HACCP i higiena żywności", "Zarządzanie food cost", "Obsługa gości (serwis à la carte)", "Planowanie menu sezonowego", "Obsługa systemów POS (Dotykačka, POSbistro)", "Zarządzanie magazynem gastronomicznym", "Praca pod presją czasową"],
    actionVerbs: ["przygotowywałem", "serwowałem", "zarządzałem", "planowałem", "szkoliłem", "dekorowałem", "kalkulowałem", "obsługiwałem", "organizowałem", "kreowałem"],
    achievementTemplates: [
      "Przygotowywałem [X]+ dań/zmianę na [X]-stanowiskowej kuchni z food cost poniżej [X]%",
      "Zarządzałem kuchnią [typ restauracji], obsługując [X] gości dziennie",
      "Opracowałem menu sezonowe ([X] pozycji), zwiększając średni rachunek o [X]%",
      "Szkoliłem zespół [X] kucharzy/kelnerów, redukując rotację personelu o [X]%",
      "Obsługiwałem eventy/bankiety do [X] osób, koordynując serwis i przygotowanie",
    ],
    certifications: ["Certyfikat HACCP", "Kurs barmański / baristyczny", "Szkolenie sommelierskie", "Kurs cukierniczy / carvingowy", "Szkolenie BHP (gastronomia)"],
    atsKeywords: ["HACCP", "food cost", "menu", "à la carte", "POS", "kuchnia", "serwis", "bankiet", "sommelier", "barista", "cukiernik"],
    toneHint: "Podawaj typ kuchni, liczbę dań/zmianę, food cost %, wielkość zespołu. Gastronomia = tempo, jakość, organizacja.",
  },

  transport: {
    id: "transport",
    label: "Transport / Kierowcy",
    escoGroup: "ESCO 8.3 — Drivers and mobile plant operators",
    onetZone: 2,
    deficit: "deficytowy",
    topRoles: ["Kierowca C+E", "Kierowca C", "Kurier", "Kierowca autobusu", "Operator wózka", "Dyspozytor", "Kierowca dostawczy"],
    coreSkills: ["Prawo jazdy kat. C/C+E/D", "Obsługa tachografu cyfrowego", "ADR (przewóz materiałów niebezpiecznych)", "Dokumentacja CMR", "Obsługa HDS", "Znajomość przepisów czasu pracy kierowców", "Nawigacja i planowanie trasy", "Drobne naprawy mechaniczne w trasie"],
    actionVerbs: ["przewoziłem", "dostarczałem", "planowałem", "rozwoziłem", "załadowywałem", "obsługiwałem", "raportowałem", "nadzorowałem", "transportowałem", "koordynowałem"],
    achievementTemplates: [
      "Realizowałem trasy krajowe/międzynarodowe ([Polska-Niemcy/Francja/Benelux]), średnio [X] km/miesiąc",
      "Dostarczałem [X] przesyłek dziennie na terenie [miasto/region] z terminowością [X]%",
      "Obsługiwałem pojazd [marka/tonnage] z ładunkami [typ], bez szkód w ciągu [X] lat",
      "Prowadziłem dokumentację CMR, tachograf cyfrowy i raporty dla spedycji",
      "Szkoliłem [X] nowych kierowców w procedurach załadunku i bezpieczeństwa",
    ],
    certifications: ["Prawo jazdy kat. C/C+E/D", "Kwalifikacja wstępna / Szkolenie okresowe (kat. C/D)", "ADR (podstawowy + cysterny)", "Uprawnienia HDS", "Karta kierowcy (tachograf cyfrowy)"],
    atsKeywords: ["C+E", "tachograf", "CMR", "ADR", "HDS", "trasy międzynarodowe", "spedycja", "TIR", "naczepy", "terminowość"],
    toneHint: "Podawaj kategorie prawa jazdy, typy ładunków, km/miesiąc, trasy. Firma transportowa szuka niezawodnego kierowcy z czystą historią.",
  },

  healthcare: {
    id: "healthcare",
    label: "Opieka zdrowotna / Farmacja",
    escoGroup: "ESCO 2.2 — Health professionals / ESCO 3.2 — Health associate professionals",
    onetZone: 4,
    deficit: "deficytowy",
    topRoles: ["Pielęgniarka", "Opiekun medyczny", "Fizjoterapeuta", "Farmaceuta", "Technik farmaceutyczny", "Ratownik medyczny", "Asystentka stomatologiczna"],
    coreSkills: ["Opieka nad pacjentem", "Podawanie leków (doustnie, dożylnie)", "Pomiary parametrów życiowych", "Dokumentacja medyczna", "Obsługa sprzętu medycznego", "Pierwsza pomoc (BLS/ALS)", "Higiena i sterylizacja", "Praca z osobami starszymi/niepełnosprawnymi"],
    actionVerbs: ["opiekowałem się", "podawałem", "monitorowałem", "dokumentowałem", "pielęgnowałem", "rehabilitowałem", "szkoliłem", "koordynowałem", "nadzorowałem", "wydawałem"],
    achievementTemplates: [
      "Sprawowałem opiekę nad [X] pacjentami na oddziale [typ], zmiana [X]h",
      "Podawałem leki dożylne i domięśniowe, prowadząc dokumentację medyczną [X] pacjentów",
      "Koordynowałem pracę zespołu pielęgniarskiego ([X] osób) na oddziale [typ]",
      "Prowadziłem rehabilitację [X] pacjentów dziennie, osiągając [X]% poprawy mobilności",
      "Wydawałem [X] recept dziennie, doradzając pacjentom w zakresie interakcji leków",
    ],
    certifications: ["Dyplom pielęgniarki/położnej", "Certyfikat BLS/ALS", "Prawo wykonywania zawodu", "Specjalizacja kliniczna", "Kurs kwalifikacyjny (szczepienia, EKG)"],
    atsKeywords: ["opieka", "pacjent", "leki", "BLS", "dokumentacja medyczna", "sterylizacja", "rehabilitacja", "farmacja", "recepta", "oddział"],
    toneHint: "Podkreślaj liczbę pacjentów, typ oddziału, specjalizacje, certyfikaty. Służba zdrowia = kompetencje + empatia + organizacja.",
  },

  finance: {
    id: "finance",
    label: "Finanse / Bankowość / Ubezpieczenia",
    escoGroup: "ESCO 2.4 — Business and administration professionals",
    onetZone: 4,
    deficit: "zrównoważony",
    topRoles: ["Księgowa", "Analityk finansowy", "Doradca bankowy", "Controller", "Specjalista ds. płac", "Audytor", "Agent ubezpieczeniowy", "Specjalista ds. windykacji"],
    coreSkills: ["Księgowość (pełna, uproszczona)", "MS Excel zaawansowany (VLOOKUP, pivot, makra VBA)", "System ERP (SAP FI/CO, Comarch Optima, Enova)", "Rozliczenia ZUS/US", "Sprawozdania finansowe", "Budżetowanie i forecasting", "Prawo podatkowe (CIT, PIT, VAT)", "Analiza finansowa"],
    actionVerbs: ["rozliczałem", "analizowałem", "budżetowałem", "kontrolowałem", "raportowałem", "optymalizowałem", "audytowałem", "kalkulowałem", "prognozowałem", "wdrożyłem"],
    achievementTemplates: [
      "Prowadziłem pełną księgowość [X] podmiotów o łącznych przychodach [X] mln PLN",
      "Wdrożyłem system [SAP/Optima], automatyzując [X]% procesów księgowych",
      "Przygotowywałem budżet roczny [X] mln PLN i miesięczne raporty odchyleń",
      "Obsługiwałem [X] klientów bankowych/ubezpieczeniowych, realizując plan sprzedaży na [X]%",
      "Zoptymalizowałem proces zamknięcia miesiąca z [X] do [X] dni roboczych",
    ],
    certifications: ["Certyfikat księgowego (SKwP)", "ACCA / CIMA", "Certyfikat doradcy podatkowego", "Licencja agenta ubezpieczeniowego", "Certyfikat SAP FI/CO"],
    atsKeywords: ["księgowość", "SAP", "Excel zaawansowany", "VAT", "CIT", "PIT", "ZUS", "budżet", "controlling", "audyt", "JPK", "e-Sprawozdania"],
    toneHint: "Podawaj wartości w PLN, liczbę obsługiwanych podmiotów/klientów, systemy (SAP, Optima, Płatnik). Finanse = precyzja + systemy + skala.",
  },

  marketing: {
    id: "marketing",
    label: "Marketing / Reklama / PR",
    escoGroup: "ESCO 2.4.3 — Marketing professionals",
    onetZone: 4,
    deficit: "zrównoważony",
    topRoles: ["Specjalista ds. marketingu", "Social Media Manager", "Content Manager", "SEO Specialist", "Performance Marketing", "Brand Manager", "Copywriter"],
    coreSkills: ["Google Ads / Meta Ads", "SEO/SEM", "Google Analytics 4", "Social media (Instagram, LinkedIn, TikTok)", "Content marketing", "Email marketing (Mailchimp, GetResponse)", "Canva / Adobe Creative Suite", "CRM (HubSpot, Salesforce)", "A/B testing", "Marketing automation"],
    actionVerbs: ["kampanizowałem", "optymalizowałem", "analizowałem", "kreowałem", "planowałem", "zarządzałem", "publikowałem", "targetowałem", "raportowałem", "konwertowałem"],
    achievementTemplates: [
      "Zarządzałem budżetem reklamowym [X] tys. PLN/miesiąc, osiągając ROAS [X]",
      "Zwiększyłem ruch organiczny o [X]% w ciągu [X] miesięcy (SEO + content)",
      "Prowadziłem social media ([platformy]) z zasięgiem [X] tys./miesiąc i engagement [X]%",
      "Wdrożyłem kampanię [typ] generującą [X] leadów przy CPL [X] PLN",
      "Napisałem [X] artykułów/postów, zwiększając konwersję strony o [X]%",
    ],
    certifications: ["Google Ads Certification", "Meta Blueprint", "Google Analytics Certification", "HubSpot Inbound Marketing", "Certyfikat SEO"],
    atsKeywords: ["Google Ads", "SEO", "SEM", "GA4", "ROAS", "CTR", "CPC", "CPL", "content marketing", "social media", "lead generation", "A/B test", "marketing automation"],
    toneHint: "Marketing = metryki. ROAS, CTR, CPL, wzrost ruchu %. Każde osiągnięcie musi mieć KPI.",
  },

  hr: {
    id: "hr",
    label: "HR / Kadry / Płace",
    escoGroup: "ESCO 2.4.2 — Human resource professionals",
    onetZone: 4,
    deficit: "zrównoważony",
    topRoles: ["Specjalista ds. HR", "Rekruter", "HR Business Partner", "Specjalista ds. kadr i płac", "Trener wewnętrzny", "Employer Branding Specialist"],
    coreSkills: ["Rekrutacja end-to-end", "Kadry i płace (Płatnik, SAP HR)", "Prawo pracy i ZUS", "Onboarding pracowników", "Szkolenia i rozwój", "Employer branding", "Systemy ATS (eRecruiter, Workday)", "Oceny okresowe i ścieżki kariery"],
    actionVerbs: ["rekrutowałem", "szkoliłem", "wdrożyłem", "koordynowałem", "doradałem", "negocjowałem", "raportowałem", "rozliczałem", "motywowałem", "onboardowałem"],
    achievementTemplates: [
      "Przeprowadziłem [X] procesów rekrutacyjnych w ciągu [X] miesięcy, time-to-hire [X] dni",
      "Wdrożyłem program onboardingowy dla [X] nowych pracowników/rok, redukując rotację o [X]%",
      "Naliczałem wynagrodzenia dla [X] pracowników, prowadząc dokumentację kadrową",
      "Organizowałem szkolenia ([X] sesji/rok) dla [X] pracowników, NPS [X]",
      "Zarządzałem employer brandingiem, zwiększając liczbę aplikacji o [X]%",
    ],
    certifications: ["Certyfikat specjalisty ds. kadr i płac", "SHRM-CP / CIPD", "Certyfikat trenera biznesu", "Kurs prawa pracy"],
    atsKeywords: ["rekrutacja", "ATS", "onboarding", "kadry", "płace", "Płatnik", "prawo pracy", "ZUS", "employer branding", "szkolenia"],
    toneHint: "Podawaj liczbę procesów rekrutacyjnych, time-to-hire, liczbę pracowników, wskaźniki retencji. HR = ludzie + procesy + metryki.",
  },

  education: {
    id: "education",
    label: "Edukacja / Nauczanie / Oświata",
    escoGroup: "ESCO 2.3 — Teaching professionals",
    onetZone: 4,
    deficit: "deficytowy",
    topRoles: [
      "Nauczyciel przedmiotu (szkoła podstawowa/ponadpodstawowa)",
      "Nauczyciel akademicki (adiunkt, wykładowca)",
      "Pedagog szkolny",
      "Wychowawca",
      "Lektor języka obcego",
      "Trener/szkoleniowiec biznesowy",
      "Dyrektor szkoły / placówki",
      "Metodyk",
    ],
    coreSkills: [
      "Tworzenie programów i scenariuszy zajęć",
      "Praca z podstawą programową MEN",
      "Ewaluacja uczniów (formatywna, sumatywna)",
      "Praca z uczniem ze specjalnymi potrzebami (SPE)",
      "IPET (Indywidualny Program Edukacyjno-Terapeutyczny)",
      "Narzędzia e-learning (Moodle, Teams, Classroom)",
      "Tablice interaktywne, TIK w edukacji",
      "Komunikacja z rodzicami",
      "Projekty Erasmus+/eTwinning",
      "Pedagogika (stopień zawodowy nauczyciela)",
    ],
    actionVerbs: [
      "prowadziłem", "uczyłem", "opracowałem", "koordynowałem", "wychowywałem", "mentorowałem", "diagnozowałem", "wdrożyłem", "ewaluowałem", "motywowałem",
    ],
    achievementTemplates: [
      "Prowadziłem zajęcia z [przedmiot] dla [X] uczniów w klasach [poziom], osiągając średnią [X] na egzaminie [zewnętrznym/maturze]",
      "Przygotowałem [X] uczniów do [olimpiada/konkurs], [X] z nich zakwalifikowało się do finału",
      "Wdrożyłem autorski program [temat], podnosząc średnią ocen z [X] do [Y]",
      "Koordynowałem projekt Erasmus+ na [X] tys. EUR, z udziałem [X] uczniów i [X] krajów",
      "Awansowałem na stopień nauczyciela [mianowany/dyplomowany] w [rok]",
    ],
    certifications: [
      "Przygotowanie pedagogiczne (kwalifikacje do nauczania)",
      "Stopnie awansu (kontraktowy, mianowany, dyplomowany)",
      "Kurs kwalifikacyjny z [pedagogika specjalna, terapia, TIK]",
      "Certyfikat CPE/CAE (dla nauczycieli j. obcych)",
      "Kurs Ratownictwa Medycznego / Pierwszej Pomocy",
    ],
    atsKeywords: [
      "podstawa programowa", "MEN", "dydaktyka", "nauczyciel", "pedagog", "awans zawodowy", "SPE", "IPET", "scenariusz lekcji", "ewaluacja", "Moodle", "Teams", "Erasmus", "tablica interaktywna",
    ],
    toneHint:
      "Podawaj konkretne przedmioty, poziomy klas, liczby uczniów, wyniki egzaminów zewnętrznych. Awans zawodowy (kontraktowy/mianowany/dyplomowany) i kwalifikacje pedagogiczne NA WIERZCHU.",
  },

  media: {
    id: "media",
    label: "Media / Dziennikarstwo / PR / Content",
    escoGroup: "ESCO 2.6 — Writers, journalists, linguists / 2.4.3 — Creative and performing artists",
    onetZone: 4,
    deficit: "zrównoważony",
    topRoles: [
      "Dziennikarz/reporter (prasa, online, TV, radio)",
      "Redaktor (prowadzący, naczelny, merytoryczny)",
      "Copywriter (B2B, B2C, kreatywny, techniczny)",
      "Content manager / specjalista ds. treści",
      "Specjalista PR / Rzecznik prasowy",
      "Social media manager",
      "Strateg treści",
      "Podcaster / video creator",
    ],
    coreSkills: [
      "Pisanie artykułów i reportaży",
      "SEO copywriting (Ahrefs, Senuto, Google Trends)",
      "Wywiady, fact-checking, riserczowanie źródeł",
      "Redagowanie (korekta stylistyczna, merytoryczna)",
      "Tworzenie komunikatów prasowych",
      "Zarządzanie kryzysowe (PR crisis)",
      "Social media (strategia, calendar, community management)",
      "CMS (WordPress, Ghost, Contentful)",
      "Narzędzia AI (ChatGPT, Claude, Jasper) — świadome użycie",
      "Metryki treści (CTR, engagement, time-on-page)",
    ],
    actionVerbs: [
      "napisałem", "zredagowałem", "przeprowadziłem", "wydałem", "opublikowałem", "zaplanowałem", "koordynowałem", "wywindowałem", "wypromowałem", "odpowiadałem",
    ],
    achievementTemplates: [
      "Napisałem [X] artykułów o łącznym zasięgu [X] tys. UU/mies. — średni czas na stronie [X] min",
      "Prowadziłem social media marki [X] — wzrost obserwatorów z [X] do [X] w [Y] miesięcy",
      "Koordynowałem [X] kampanii PR, z czego [X] z publikacjami w top [media: Gazeta Wyborcza, Rzeczpospolita, Onet]",
      "Rebranduję content strategy — wzrost organicznego ruchu o [X]% w [Y] kwartałach",
      "Przeprowadziłem [X] wywiadów z ekspertami branży [X], z cyklu dostępne w [medium]",
    ],
    certifications: [
      "Dyplom dziennikarstwa (UW, UJ, WSIiZ, inne)",
      "Kurs SEO copywritingu (Senuto, SEMrush Academy)",
      "Certyfikat Google Analytics / Google Ads",
      "Akredytacja prasowa (SDP, KJRP)",
      "Kurs PR kryzysowego",
    ],
    atsKeywords: [
      "copywriting", "SEO", "WordPress", "CMS", "content marketing", "dziennikarstwo", "PR", "social media", "community management", "Ahrefs", "Senuto", "storytelling", "copywriter", "engagement",
    ],
    toneHint:
      "Mierzalne efekty: zasięgi (UU/mies), engagement, liczby publikacji, pozycjonowanie w SERP. Pokaż portfolio — linki do artykułów lub case studies w custom sections.",
  },

  ecommerce: {
    id: "ecommerce",
    label: "E-commerce / Handel elektroniczny",
    escoGroup: "ESCO 2.4.2 — Marketing, sales — online channels",
    onetZone: 4,
    deficit: "deficytowy",
    topRoles: [
      "E-commerce Manager",
      "Product Manager (marketplace, sklep online)",
      "Specjalista ds. marketplace (Allegro, Amazon, eBay)",
      "Specjalista Performance Marketing (Google Ads, Meta Ads)",
      "Specjalista Category Management",
      "E-commerce Analyst (PowerBI, SQL, GA4)",
      "Customer Experience Manager",
      "Specjalista B2C/D2C",
    ],
    coreSkills: [
      "Platformy: Shopify, Magento, PrestaShop, WooCommerce, IdoSell",
      "Marketplace: Allegro (Smart, Allegro Ads), Amazon (Seller Central), eBay",
      "Performance marketing (Google Ads, Meta Business, TikTok Ads)",
      "Analytics (GA4, GTM, Hotjar, Looker)",
      "SQL + PowerBI / Tableau",
      "SEO produktowy (Merchant Center, structured data)",
      "A/B testing (Optimize, VWO, GrowthBook)",
      "Retencja i lifecycle (email, push, SMS)",
      "Payment gateways (Przelewy24, PayU, Stripe, Blik)",
      "Logistyka e-commerce (Furgonetka, InPost, DPD, integracje WMS)",
    ],
    actionVerbs: [
      "zwiększyłem", "zoptymalizowałem", "wdrożyłem", "prowadziłem", "analizowałem", "rozwijałem", "skalowałem", "przekształciłem", "testowałem", "automatyzowałem",
    ],
    achievementTemplates: [
      "Zwiększyłem konwersję sklepu z [X]% do [Y]% (+[Z] pp) przez optymalizację checkoutu i A/B testy",
      "Skalowałem kampanie Google Ads/Meta — ROAS [X:1], budżet miesięczny [X] PLN, przychód [X] mln",
      "Rozwijałem sprzedaż na Allegro — z [X] tys. do [X] mln PLN GMV w [Y] miesięcy",
      "Wdrożyłem automatyzację email marketingu (Klaviyo/Mailchimp) — [X]% przychodu z kanału",
      "Prowadziłem category management dla [X] SKU — wzrost marży o [X] pp",
    ],
    certifications: [
      "Google Ads (Search, Shopping, Display)",
      "Google Analytics 4 Certified",
      "Meta Blueprint Certification",
      "Allegro Marketing Academy",
      "Shopify Partners / Experts",
      "Certyfikat Scrum Master / Product Owner",
    ],
    atsKeywords: [
      "Shopify", "Magento", "Allegro", "Amazon", "Google Ads", "Meta Ads", "GA4", "PowerBI", "SQL", "A/B testing", "ROAS", "CTR", "CR", "AOV", "GMV", "D2C", "e-commerce",
    ],
    toneHint:
      "E-commerce = LICZBY. GMV, ROAS, CR, AOV, CAC, LTV — nazwy KPI po skrótach. Pokaż kanały (SEO/Ads/Email) i wyniki.",
  },

  "public-sector": {
    id: "public-sector",
    label: "Administracja publiczna / Urzędy / Samorząd",
    escoGroup: "ESCO 3.3 — Business and administration associate professionals / 2.6.1 — Legal professionals",
    onetZone: 3,
    deficit: "zrównoważony",
    topRoles: [
      "Inspektor / Specjalista w urzędzie",
      "Referent / Starszy referent",
      "Kierownik wydziału",
      "Asystent sędziego",
      "Sekretarz gminy/miasta",
      "Specjalista ds. zamówień publicznych",
      "Koordynator projektów unijnych",
      "Urzędnik samorządowy",
    ],
    coreSkills: [
      "Kodeks Postępowania Administracyjnego (KPA)",
      "Kodeks Cywilny (KC), Kodeks Pracy (KP)",
      "Prawo zamówień publicznych (PZP)",
      "Ustawa o pracownikach samorządowych",
      "Obsługa ePUAP, ePodatki, EZD",
      "Korespondencja urzędowa (decyzje administracyjne)",
      "RODO w administracji (IODO, DPIA)",
      "Rozliczanie środków unijnych (POWER, FEnIKS)",
      "Praca z rejestrami państwowymi",
      "Obsługa klienta urzędowego",
    ],
    actionVerbs: [
      "rozpatrywałem", "wydawałem", "prowadziłem", "koordynowałem", "reprezentowałem", "kontrolowałem", "przygotowywałem", "archiwizowałem", "opiniowałem", "wdrażałem",
    ],
    achievementTemplates: [
      "Prowadziłem [X] postępowań administracyjnych rocznie, wskaźnik rozpatrzenia w terminie KPA [X]%",
      "Koordynowałem projekt unijny o wartości [X] mln PLN (POWER/FEnIKS) — [X] uczestników, rozliczenie 100%",
      "Przeprowadziłem [X] postępowań o udzielenie zamówienia publicznego (tryby PZP) — łączna wartość [X] mln PLN",
      "Wprowadziłem elektroniczny obieg dokumentów (EZD) — skrócenie czasu obsługi wniosku z [X] na [Y] dni",
      "Obsłużyłem [X] interesantów dziennie w zakresie [konkretna dziedzina]",
    ],
    certifications: [
      "Służba przygotowawcza (korpus służby cywilnej)",
      "Certyfikat IODO / DPIA",
      "Kurs zamówień publicznych (PZP)",
      "Certyfikat koordynatora projektów UE",
      "Egzamin zawodowy (specjalistyczny w administracji)",
    ],
    atsKeywords: [
      "KPA", "KC", "PZP", "ePUAP", "EZD", "RODO", "IODO", "POWER", "FEnIKS", "administracja publiczna", "samorząd", "decyzja administracyjna", "rejestr publiczny", "zamówienia publiczne",
    ],
    toneHint:
      "Cytuj konkretne ustawy i przepisy. Służba cywilna, korpus, egzaminy zawodowe — te rzeczy liczą się w CV urzędniczym. Pokaż terminowość i skalę postępowań.",
  },

  design: {
    id: "design",
    label: "Design / UX / UI / Produkt",
    escoGroup: "ESCO 2.1.6 — Graphic and multimedia designers",
    onetZone: 4,
    deficit: "zrównoważony",
    topRoles: [
      "UX Designer",
      "UI Designer",
      "Product Designer",
      "Senior UX Designer",
      "Senior Product Designer",
      "UX Researcher",
      "Service Designer",
      "Design System Lead",
      "Interaction Designer",
      "Junior UX Designer",
    ],
    coreSkills: [
      "Figma (komponenty, auto-layout, variables, variants)",
      "Design system (Tokens, Storybook, dokumentacja)",
      "Badania UX (wywiady, usability testing, ankiety)",
      "Prototypowanie (Figma, Protopie, Framer)",
      "Wireframing i architektura informacji",
      "Dostępność (WCAG 2.2, ARIA)",
      "Design Ops",
      "A/B testing i heatmapy (Hotjar, FullStory)",
      "User flows, journey maps, service blueprint",
      "Design handoff (Figma Dev Mode, Zeplin)",
    ],
    actionVerbs: [
      "zaprojektowałem",
      "przeprowadziłem",
      "zwalidowałem",
      "zaprototypowałem",
      "zmapowałem",
      "zoptymalizowałem",
      "wdrożyłem",
      "skonsolidowałem",
      "zbudowałem",
      "przetestowałem",
    ],
    achievementTemplates: [
      "Przeprojektowałem [flow/sekcję] w aplikacji [typ], zwiększając konwersję o [X]% ([X] mln użytkowników)",
      "Zbudowałem design system w Figmie ([X] komponentów, [X] tokenów), skracając time-to-design o [X]%",
      "Przeprowadziłem [X] wywiadów pogłębionych + [X] sesji usability testing, wyciągając [X] insightów produktowych",
      "Zwiększyłem dostępność aplikacji do poziomu WCAG 2.2 AA — [X] audytów, [X] poprawek",
      "Koordynowałem zespół [X] projektantów + [X] developerów przy wdrożeniu [projektu]",
    ],
    certifications: [
      "Nielsen Norman Group UX Certification",
      "Interaction Design Foundation (IDF)",
      "Google UX Design Certificate",
      "Figma Professional Certification",
      "CPACC (dostępność cyfrowa)",
    ],
    atsKeywords: [
      "Figma",
      "design system",
      "design tokens",
      "wireframing",
      "prototypowanie",
      "user research",
      "badania UX",
      "usability testing",
      "user flows",
      "journey map",
      "WCAG",
      "accessibility",
      "information architecture",
      "A/B testing",
      "Storybook",
      "auto-layout",
      "Figma variables",
      "design handoff",
      "Protopie",
      "Sketch",
      "Adobe XD",
    ],
    toneHint:
      "Pokazuj konkretne metryki produktowe (konwersja, retencja, NPS) i zasięg (liczba użytkowników, MAU). Recruiter w designie szuka dowodów mierzalnego wpływu projektu na biznes, nie tylko ładnych ekranów.",
  },

  beauty: {
    id: "beauty",
    label: "Uroda / Fryzjerstwo / Kosmetyka",
    escoGroup: "ESCO 5.1.4 — Hairdressers, beauticians",
    onetZone: 2,
    deficit: "deficytowy",
    topRoles: ["Fryzjer", "Kosmetyczka", "Stylistka paznokci", "Barber", "Makijażystka", "Masażysta", "Podolog"],
    coreSkills: ["Strzyżenie damskie/męskie", "Koloryzacja (farbowanie, pasemka, balayage)", "Stylizacja brwi i rzęs", "Manicure/pedicure (hybrydowy, żelowy)", "Zabiegi kosmetyczne (kwasy, mezoterapia)", "Masaż (klasyczny, sportowy, leczniczy)", "Obsługa klienta i doradztwo", "Higiena i sterylizacja narzędzi"],
    actionVerbs: ["stylizowałem", "wykonywałem", "doradzałem", "obsługiwałem", "szkoliłem", "kreowałem", "pielęgnowałem", "kolorowałem", "masowałem", "dekorowałem"],
    achievementTemplates: [
      "Obsługiwałem [X] klientów dziennie, utrzymując [X]% powracalność",
      "Specjalizowałem się w [technika], wykonując [X] zabiegów/miesiąc",
      "Budowałem portfolio klientów od [X] do [X] stałych klientek w ciągu [X] miesięcy",
      "Szkoliłem [X] młodszych stylistów/kosmetyczki w technikach [typ]",
      "Prowadziłem social media salonu (Instagram [X] followers), generując [X]% rezerwacji online",
    ],
    certifications: ["Dyplom czeladniczy / mistrzowski (fryzjerstwo)", "Certyfikat kosmetyczki", "Kurs stylizacji brwi i rzęs", "Certyfikat masażysty", "Szkolenie z mezoterapii / kwasów"],
    atsKeywords: ["fryzjer", "koloryzacja", "balayage", "manicure", "pedicure", "mezoterapia", "stylizacja", "masaż", "podologia", "Instagram"],
    toneHint: "Podkreślaj techniki, specjalizacje, liczbę klientów, powracalność. Branża beauty = portfel klientów + umiejętności specjalistyczne.",
  },

  legal: {
    id: "legal",
    label: "Prawo / Radca prawny / Notariat",
    escoGroup: "ESCO 2.6.1 — Legal professionals",
    onetZone: 5,
    deficit: "zrównoważony",
    topRoles: [
      "Radca prawny",
      "Adwokat",
      "Aplikant radcowski",
      "Aplikant adwokacki",
      "Notariusz",
      "Prawnik in-house",
      "Specjalista ds. prawnych",
      "Compliance Officer",
      "Paralegal",
    ],
    coreSkills: [
      "Sporządzanie pism procesowych i umów",
      "Reprezentacja przed sądami i organami administracji",
      "Analiza prawna i opinie",
      "Due diligence (przejęcia, nieruchomości)",
      "RODO / ochrona danych osobowych",
      "Prawo gospodarcze, cywilne, pracy",
      "Postępowania administracyjne (KPA)",
      "Obsługa LEX / Legalis / System Informacji Prawnej",
      "Negocjacje kontraktowe",
      "Compliance AML, KYC",
    ],
    actionVerbs: [
      "reprezentowałem",
      "sporządziłem",
      "negocjowałem",
      "opiniowałem",
      "analizowałem",
      "doradzałem",
      "prowadziłem",
      "wygrywałem",
      "wdrażałem",
      "audytowałem",
    ],
    achievementTemplates: [
      "Reprezentowałem klienta w [X] sprawach [typu: cywilne/gospodarcze/administracyjne], wygrywając [X]% z nich",
      "Sporządzałem umowy handlowe o wartości do [X] mln PLN (B2B, M&A, IT)",
      "Przeprowadziłem due diligence [X] transakcji (nieruchomości / akwizycje spółek)",
      "Wdrożyłem politykę RODO w [typ firmy] obsługującej [X] klientów, bez incydentów w ciągu [X] lat",
      "Prowadziłem obsługę prawną [X] spółek grupy kapitałowej (kontrakty, korporacyjne, pracownicze)",
    ],
    certifications: [
      "Wpis na listę radców prawnych / adwokatów (OIRP / ORA)",
      "Egzamin radcowski / adwokacki",
      "Aplikacja radcowska / adwokacka",
      "Inspektor Ochrony Danych (IOD)",
      "Certyfikat compliance (ACAMS, CCO)",
    ],
    atsKeywords: [
      "radca prawny",
      "umowy",
      "due diligence",
      "RODO",
      "compliance",
      "KPA",
      "postępowanie sądowe",
      "prawo gospodarcze",
      "prawo pracy",
      "negocjacje",
      "LEX",
      "Legalis",
    ],
    toneHint:
      "Podawaj rodzaje spraw (liczba, obszar prawa), wartości kontraktów, wyniki postępowań. Kancelaria i dział prawny szukają osób z udokumentowanym obszarem specjalizacji.",
  },

  accounting: {
    id: "accounting",
    label: "Księgowość / Kadry i płace",
    escoGroup: "ESCO 2.4.1 — Finance professionals / 3.3.1 — Financial clerks",
    onetZone: 4,
    deficit: "deficytowy",
    topRoles: [
      "Główna księgowa",
      "Księgowy",
      "Młodszy księgowy",
      "Samodzielna księgowa",
      "Specjalista ds. kadr i płac",
      "Analityk finansowy",
      "Specjalista ds. podatków",
      "Audytor wewnętrzny",
    ],
    coreSkills: [
      "Pełna księgowość (KH) i uproszczona (KPiR)",
      "VAT, CIT, PIT — rozliczenia i deklaracje (JPK, e-Faktura)",
      "Kadry i płace (ZUS, US, PFRON, PPK)",
      "Obsługa systemów: Symfonia, enova365, Comarch Optima, SAP, Płatnik",
      "Księgi rachunkowe zgodne z ustawą o rachunkowości",
      "Bilans, rachunek zysków i strat, cash flow",
      "Inwentaryzacja i korekty",
      "MSR / MSSF (gdy firma raportuje wg standardów międzynarodowych)",
      "Współpraca z audytorami i US",
    ],
    actionVerbs: [
      "księgowałem",
      "rozliczałem",
      "sporządzałem",
      "kontrolowałem",
      "prowadziłem",
      "uzgadniałem",
      "zamykałem",
      "analizowałem",
      "raportowałem",
      "audytowałem",
    ],
    achievementTemplates: [
      "Prowadziłam pełną księgowość [typ firmy] z obrotem [X] mln PLN rocznie",
      "Sporządzałam sprawozdania finansowe zgodne z UoR / MSSF dla [X] podmiotów grupy",
      "Rozliczałam płace [X] pracowników miesięcznie (UoP, UZ, B2B) bez błędów w ZUS/US",
      "Wdrożyłam e-fakturę (KSeF) w firmie [typ], skracając obieg dokumentów o [X]%",
      "Przygotowywałam deklaracje VAT / CIT / JPK dla [X] spółek bez korekt urzędowych",
    ],
    certifications: [
      "Certyfikat Głównej Księgowej (SKwP)",
      "Certyfikat księgowy (Ministerstwo Finansów — sprzed 2014)",
      "ACCA / CIMA (międzynarodowe)",
      "Doradca podatkowy",
      "Inspektor Ochrony Danych (dla działu kadr)",
    ],
    atsKeywords: [
      "pełna księgowość",
      "KPiR",
      "VAT",
      "CIT",
      "PIT",
      "JPK",
      "e-Faktura",
      "KSeF",
      "Symfonia",
      "enova365",
      "Comarch Optima",
      "SAP",
      "Płatnik",
      "ZUS",
      "kadry i płace",
      "sprawozdanie finansowe",
      "bilans",
      "MSR",
      "MSSF",
    ],
    toneHint:
      "Podawaj skalę (obrót firmy, liczba pracowników na płacach, liczba dokumentów/miesiąc), systemy księgowe, typy rozliczeń. Księgowość = rzetelność + znajomość przepisów + skala.",
  },

  data: {
    id: "data",
    label: "Dane / Analityka / BI / Data Science",
    escoGroup: "ESCO 2.5.2 — Database and network professionals / 2.1.2 — Mathematicians, statisticians",
    onetZone: 4,
    deficit: "deficytowy",
    topRoles: [
      "Data Analyst",
      "Analityk danych",
      "BI Developer",
      "Analityk biznesowy",
      "Data Engineer",
      "Data Scientist",
      "ML Engineer",
      "Analytics Engineer",
    ],
    coreSkills: [
      "SQL zaawansowany (okna, CTE, optymalizacja)",
      "Python (pandas, numpy, scikit-learn, PySpark)",
      "Narzędzia BI: Power BI, Tableau, Looker",
      "Hurtownie danych (Snowflake, BigQuery, Redshift)",
      "dbt, Airflow, orkiestracja ETL/ELT",
      "Statystyka i testy A/B",
      "Modelowanie danych (Kimball, Data Vault)",
      "Machine Learning (klasyfikacja, regresja, clustering)",
      "Wizualizacja danych i storytelling",
      "Git, dokumentacja modeli danych",
    ],
    actionVerbs: [
      "analizowałem",
      "zamodelowałem",
      "zbudowałem",
      "zautomatyzowałem",
      "wdrożyłem",
      "prognozowałem",
      "zoptymalizowałem",
      "odkryłem",
      "wizualizowałem",
      "przetrenowałem",
    ],
    achievementTemplates: [
      "Zbudowałem pulpit BI w [Power BI/Tableau] dla [X] użytkowników biznesowych, skracając czas raportowania o [X]%",
      "Zamodelowałem hurtownię [Snowflake/BigQuery] z [X] tabelami obsługującą [X] TB danych",
      "Przetrenowałem model [ML] o AUC [X], zwiększając trafność predykcji o [X]%",
      "Zautomatyzowałem pipeline ETL w [Airflow/dbt], redukując ręczną pracę z [X]h do [X]h/tydzień",
      "Przeprowadziłem [X] testów A/B, identyfikując usprawnienia o łącznym wpływie [X] mln PLN",
    ],
    certifications: [
      "Microsoft Certified: Data Analyst Associate",
      "Google Cloud Professional Data Engineer",
      "AWS Certified Data Analytics",
      "Tableau Desktop Specialist",
      "dbt Certified Developer",
    ],
    atsKeywords: [
      "SQL",
      "Python",
      "pandas",
      "Power BI",
      "Tableau",
      "Snowflake",
      "BigQuery",
      "dbt",
      "Airflow",
      "ETL",
      "A/B testing",
      "machine learning",
      "hurtownia danych",
      "data modeling",
      "Looker",
    ],
    toneHint:
      "Podawaj rozmiar danych (GB/TB, wierszy), skalę użytkowników pulpitów, metryki modeli (AUC, F1, MAPE). Dział danych szuka osób łączących technologię z wnioskami biznesowymi.",
  },

  insurance: {
    id: "insurance",
    label: "Ubezpieczenia / Likwidacja szkód",
    escoGroup: "ESCO 3.3.2 — Financial and insurance services workers",
    onetZone: 4,
    deficit: "zrównoważony",
    topRoles: [
      "Agent ubezpieczeniowy",
      "Doradca ubezpieczeniowy",
      "Likwidator szkód",
      "Underwriter",
      "Specjalista ds. ubezpieczeń",
      "Broker ubezpieczeniowy",
      "Aktuariusz",
      "Specjalista ds. claims",
    ],
    coreSkills: [
      "Sprzedaż polis OC/AC, życiowych, majątkowych, zdrowotnych",
      "Likwidacja szkód (komunikacyjne, majątkowe)",
      "Underwriting — ocena ryzyka",
      "Obsługa systemów: Insly, SAP Insurance, COMP, SIU",
      "Znajomość ustawy o działalności ubezpieczeniowej",
      "Analiza OWU i warunków polis",
      "Obsługa klienta i rozpatrywanie reklamacji",
      "Ustawa o dystrybucji ubezpieczeń (IDD)",
      "Przeciwdziałanie praniu pieniędzy (AML)",
    ],
    actionVerbs: [
      "sprzedawałem",
      "likwidowałem",
      "wyceniałem",
      "negocjowałem",
      "oceniałem",
      "obsługiwałem",
      "rozpatrywałem",
      "doradzałem",
      "analizowałem",
      "pozyskiwałem",
    ],
    achievementTemplates: [
      "Sprzedałem polisy o łącznej składce [X] mln PLN w [typ segmentu], realizując [X]% planu",
      "Zlikwidowałem [X] szkód komunikacyjnych/majątkowych w terminie średnio [X] dni",
      "Pozyskałem [X] nowych klientów korporacyjnych z portfelem o wartości [X] mln PLN",
      "Wdrożyłem procedury IDD i AML w agencji, bez negatywnych wyników kontroli KNF",
      "Rozpatrzyłem [X] reklamacji klientów z poziomem zadowolenia [X]% (CSAT)",
    ],
    certifications: [
      "Egzamin KNF — ubezpieczenia życiowe / majątkowe",
      "Certyfikat EFPA (European Financial Planner)",
      "Aktuariusz — egzaminy państwowe",
      "Certyfikat IDD",
      "Licencja brokera ubezpieczeniowego",
    ],
    atsKeywords: [
      "OC",
      "AC",
      "ubezpieczenie na życie",
      "ubezpieczenie majątkowe",
      "likwidacja szkód",
      "underwriting",
      "OWU",
      "IDD",
      "AML",
      "KNF",
      "polisa",
      "reasekuracja",
      "CSAT",
    ],
    toneHint:
      "Podawaj wartość składek, liczbę polis, terminowość likwidacji, CSAT. Branża ubezpieczeniowa = precyzja, regulacje, portfolio klientów.",
  },

  engineering: {
    id: "engineering",
    label: "Inżynieria / Projektowanie techniczne",
    escoGroup: "ESCO 2.1.4 — Engineering professionals (except electrotechnology)",
    onetZone: 4,
    deficit: "deficytowy",
    topRoles: [
      "Inżynier mechanik",
      "Inżynier elektryk",
      "Inżynier automatyk",
      "Inżynier procesu",
      "Konstruktor",
      "Projektant instalacji",
      "Inżynier utrzymania ruchu",
      "Inżynier jakości",
      "Inżynier R&D",
    ],
    coreSkills: [
      "AutoCAD, SolidWorks, Inventor, CATIA",
      "Projektowanie 3D i dokumentacja techniczna",
      "Znajomość norm (ISO, EN, DIN)",
      "PLC (Siemens S7, Allen-Bradley), SCADA",
      "Lean Manufacturing, Six Sigma",
      "FMEA, APQP, PPAP",
      "MES / ERP (SAP PP, QM)",
      "Uprawnienia SEP (E/D kat. do 1kV)",
      "Pomiary laboratoryjne i kontrola jakości",
      "Dokumentacja techniczna w j. angielskim",
    ],
    actionVerbs: [
      "zaprojektowałem",
      "wdrożyłem",
      "zoptymalizowałem",
      "uruchomiłem",
      "przetestowałem",
      "zdiagnozowałem",
      "skalibrowałem",
      "koordynowałem",
      "opracowałem",
      "nadzorowałem",
    ],
    achievementTemplates: [
      "Zaprojektowałem [element/maszynę] w SolidWorks, zmniejszając masę o [X]% przy zachowaniu wytrzymałości",
      "Wdrożyłem usprawnienie linii produkcyjnej [X], zwiększając wydajność o [X] szt/zmianę",
      "Skróciłem czas przezbrojenia (SMED) z [X] do [X] min na linii [typ]",
      "Opracowałem dokumentację techniczną zgodną z [norma], przeszła audyt [TÜV/BV/DNV]",
      "Uruchomiłem maszynę [typ] z programem PLC [Siemens/AB], bez przestojów w pierwszym miesiącu",
    ],
    certifications: [
      "Uprawnienia SEP kat. E/D (1 kV / średnie napięcie)",
      "Uprawnienia energetyczne G1/G2/G3",
      "TÜV / DNV / BV — audytor jakości",
      "Lean Six Sigma (Green/Black Belt)",
      "Uprawnienia UDT (dźwigi, wózki, podesty)",
    ],
    atsKeywords: [
      "SolidWorks",
      "AutoCAD",
      "Inventor",
      "CATIA",
      "PLC",
      "Siemens S7",
      "SCADA",
      "Lean",
      "Six Sigma",
      "FMEA",
      "SMED",
      "ISO 9001",
      "SEP",
      "UDT",
      "SAP PP",
      "R&D",
    ],
    toneHint:
      "Podawaj konkretne systemy CAD, normy, parametry techniczne, wydajność linii (szt/min, OEE), oszczędności (czas, materiały). Inżynier = pomiar + optymalizacja.",
  },

  security: {
    id: "security",
    label: "Ochrona / Bezpieczeństwo (fizyczne + cyber)",
    escoGroup: "ESCO 5.4 — Protective services workers / 2.5.2 — ICT security specialists",
    onetZone: 3,
    deficit: "deficytowy",
    topRoles: [
      "Pracownik ochrony",
      "Kwalifikowany pracownik ochrony fizycznej",
      "Konwojent",
      "Dowódca zmiany",
      "Specjalista ds. bezpieczeństwa",
      "IT Security Specialist",
      "SOC Analyst",
      "Pentester",
      "Specjalista ds. BHP",
    ],
    coreSkills: [
      "Uprawnienia kwalifikowanego pracownika ochrony (KPOF)",
      "Obsługa systemów monitoringu (CCTV, SSWiN, KD)",
      "Interwencja i samoobrona",
      "Obsługa broni palnej (z licencją)",
      "Znajomość ustawy o ochronie osób i mienia",
      "BHP, ppoż., ewakuacja",
      "SIEM (Splunk, QRadar, Sentinel)",
      "Analiza incydentów (IR) i forensyka",
      "Polityki bezpieczeństwa (ISO 27001)",
      "Pentesting (OWASP, Burp, Nessus)",
    ],
    actionVerbs: [
      "ochraniałem",
      "monitorowałem",
      "interweniowałem",
      "zabezpieczałem",
      "analizowałem",
      "audytowałem",
      "wdrażałem",
      "reagowałem",
      "szkoliłem",
      "eskalowałem",
    ],
    achievementTemplates: [
      "Prowadziłem ochronę obiektu [typ] ([X] m² / [X] pracowników) bez incydentów w ciągu [X] lat",
      "Monitorowałem [X] kamer CCTV i [X] systemów alarmowych dla [X] klientów z czasem reakcji [X] min",
      "Wykryłem i zgłosiłem [X] incydentów bezpieczeństwa (IT/fizyczne), wszystkie zażegnane w [X] min",
      "Wdrożyłem politykę bezpieczeństwa ISO 27001 w organizacji [X] pracowników",
      "Przeprowadziłem [X] testów penetracyjnych aplikacji webowych z [X] krytycznymi lukami wykrytymi",
    ],
    certifications: [
      "Licencja kwalifikowanego pracownika ochrony fizycznej",
      "Szkolenie z broni palnej (MSWiA)",
      "Pierwsza pomoc (BLS/KPP)",
      "CISSP / CEH / OSCP",
      "ISO 27001 Lead Auditor",
      "CompTIA Security+",
    ],
    atsKeywords: [
      "ochrona",
      "KPOF",
      "CCTV",
      "SSWiN",
      "monitoring",
      "interwencja",
      "BHP",
      "ppoż",
      "SIEM",
      "incident response",
      "ISO 27001",
      "pentesting",
      "OWASP",
      "SOC",
      "cyberbezpieczeństwo",
    ],
    toneHint:
      "Podawaj typ obiektu, liczbę kamer/pracowników, liczbę/typ incydentów, czas reakcji. Branża ochrony/bezpieczeństwa = rzetelność + certyfikaty + doświadczenie z incydentami.",
  },

  energy: {
    id: "energy",
    label: "Energetyka / OZE",
    escoGroup: "ESCO 7.4 — Electrical and electronic trades workers / 2.1.3 — Electrical engineers",
    onetZone: 3,
    deficit: "deficytowy",
    topRoles: [
      "Elektromontażysta OZE",
      "Serwisant farm wiatrowych",
      "Operator turbiny wiatrowej",
      "Elektryk przemysłowy",
      "Inżynier OZE / fotowoltaiki",
      "Projektant instalacji PV",
      "Operator bloku energetycznego",
      "Technik energetyk",
      "Instalator pomp ciepła",
    ],
    coreSkills: [
      "Montaż paneli fotowoltaicznych (na dachu i gruncie)",
      "Serwis turbin wiatrowych (on-shore / off-shore)",
      "Uprawnienia SEP E do 1kV i powyżej",
      "Uprawnienia SEP D (dozorowe) do 1kV i powyżej",
      "Praca na wysokości (wieże wiatrowe, dachy)",
      "Obsługa inwerterów (SolarEdge, Enphase, Fronius, Huawei, SMA)",
      "Czytanie schematów elektrycznych i jednokreskowych",
      "PPOŻ na stacjach transformatorowych",
      "Smart grid i SCADA w energetyce",
      "Magazyny energii (BESS)",
      "Termografia instalacji elektrycznych",
      "Pomiary elektryczne (izolacja, pętla zwarcia, impedancja)",
    ],
    actionVerbs: [
      "montowałem",
      "instalowałem",
      "serwisowałem",
      "uruchamiałem",
      "konserwowałem",
      "diagnozowałem",
      "projektowałem",
      "pomiarowałem",
      "zabezpieczałem",
      "audytowałem",
    ],
    achievementTemplates: [
      "Zamontowałem [X] instalacji fotowoltaicznych o łącznej mocy [X] kWp u klientów [indywidualnych/komercyjnych]",
      "Serwisowałem [X] turbin wiatrowych na farmie [X] MW — MTBF [X]h, dostępność [X]%",
      "Uruchomiłem stację transformatorową [X] kV/[X] kV o mocy [X] MVA",
      "Przeprowadziłem pomiary elektryczne (rezystancja izolacji, pętla zwarcia) w [X] obiektach — 100% zgodność z normą PN-HD",
      "Zaprojektowałem instalację PV [X] kWp z magazynem energii [X] kWh dla klienta [typ obiektu]",
    ],
    certifications: [
      "SEP E do 1 kV (eksploatacja)",
      "SEP E powyżej 1 kV",
      "SEP D do 1 kV (dozór)",
      "SEP D powyżej 1 kV",
      "Certyfikat UDT instalatora OZE (PV, pompy ciepła, kolektory słoneczne)",
      "Uprawnienia wysokościowe (alpinistyczne / dostęp linowy IRATA)",
      "Kurs obsługi dźwigów teleskopowych / HDS",
      "Termografista ITC Level 1 / Level 2",
      "Uprawnienia spawalnicze MIG/TIG dla konstrukcji stalowych",
    ],
    atsKeywords: [
      "fotowoltaika",
      "PV",
      "OZE",
      "SEP E",
      "SEP D",
      "turbina wiatrowa",
      "SCADA",
      "inwerter",
      "magazyn energii",
      "BESS",
      "elektromontaż",
      "smart grid",
      "pomiary elektryczne",
      "termografia",
      "instalacja",
      "pompa ciepła",
      "kolektor słoneczny",
      "stacja trafo",
    ],
    toneHint:
      "Podawaj moce w kW/MW, liczby instalacji, typy inwerterów i paneli, konkretne uprawnienia SEP. Branża deficytowa w 2026 — pracodawca szuka uprawnień i praktyki, nie teorii.",
  },

  telecom: {
    id: "telecom",
    label: "Telekomunikacja / Cyberbezpieczeństwo",
    escoGroup: "ESCO 2.5.2 — ICT security specialists / 2.5.1 — ICT service managers / 3.3.3 — Telecom trades",
    onetZone: 4,
    deficit: "deficytowy",
    topRoles: [
      "Inżynier sieci",
      "Specjalista cyberbezpieczeństwa",
      "SOC Analyst (L1/L2/L3)",
      "Pentester",
      "Administrator sieci",
      "Inżynier 5G / LTE",
      "Technik światłowodowy",
      "DevSecOps Engineer",
      "Cloud Security Architect",
      "Compliance Manager (NIS2)",
    ],
    coreSkills: [
      "CCNA / CCNP routing & switching",
      "Firewalle (Fortinet FortiGate, Palo Alto, Cisco ASA, Check Point)",
      "SIEM (Splunk, Microsoft Sentinel, QRadar, Elastic)",
      "SOC incident response (playbooks, MITRE ATT&CK)",
      "Pentesting (Burp Suite, Metasploit, Nessus, Nmap, OWASP ZAP)",
      "Linux networking (iptables, nftables, bgp, ospf)",
      "Chmura — bezpieczeństwo AWS / Azure / GCP",
      "Zero Trust Architecture",
      "SD-WAN (Cisco Viptela, Fortinet Secure SD-WAN)",
      "5G/LTE Core i RAN",
      "Światłowody FTTH (spawanie, reflektometria OTDR)",
      "ISO 27001, NIS2, DORA compliance",
      "DevSecOps (SAST, DAST, IaC scanning)",
      "Kubernetes security",
    ],
    actionVerbs: [
      "konfigurowałem",
      "wdrażałem",
      "monitorowałem",
      "audytowałem",
      "analizowałem",
      "reagowałem",
      "eskalowałem",
      "zabezpieczałem",
      "projektowałem",
      "testowałem",
    ],
    achievementTemplates: [
      "Wdrożyłem SIEM (Splunk / Sentinel) obsługujący [X] EPS z [X] regułami detekcji dla organizacji [X] pracowników",
      "Reagowałem na [X] incydentów bezpieczeństwa rocznie — MTTR [X] min, MTBF [X]h",
      "Zaprojektowałem sieć [X] lokalizacji z [X] VLAN-ami i redundancją HA — dostępność 99.9%",
      "Przeprowadziłem [X] testów penetracyjnych aplikacji webowych z [X] krytycznymi i [X] wysokimi podatnościami",
      "Audytowałem zgodność ISO 27001 / NIS2 w organizacji [X] pracowników — 0 niezgodności krytycznych",
    ],
    certifications: [
      "CCNA / CCNP / CCIE",
      "CISSP / CISM / CEH / OSCP",
      "AWS Security / Azure Security / GCP Security",
      "ISO 27001 Lead Auditor",
      "CompTIA Security+ / Network+",
      "Fortinet NSE 4-7",
      "Palo Alto PCNSE",
      "Certyfikat światłowodowy (spawanie, OTDR)",
      "Scrum Master / SAFe",
    ],
    atsKeywords: [
      "CCNA",
      "CCNP",
      "CISSP",
      "SOC",
      "SIEM",
      "pentesting",
      "firewall",
      "5G",
      "LTE",
      "światłowód",
      "FTTH",
      "OTDR",
      "AWS Security",
      "Azure Sentinel",
      "Zero Trust",
      "SD-WAN",
      "NIS2",
      "ISO 27001",
      "DevSecOps",
      "incident response",
      "OWASP",
      "Kubernetes security",
      "MITRE ATT&CK",
    ],
    toneHint:
      "Branża 2026 wymaga certyfikatów na wierzchu — CISSP, CCNA, AWS Security. Konkretne narzędzia (Splunk, Fortinet), liczby EPS/MTTR/MTBF, metryki dostępności. Unikaj ogólników typu 'cyberbezpieczeństwo' — użyj 'SOC Analyst L2 z SIEM Splunk i MITRE ATT&CK playbooks'.",
  },

  agriculture: {
    id: "agriculture",
    label: "Rolnictwo / Leśnictwo",
    escoGroup: "ESCO 6.1 — Market-oriented skilled agricultural workers / 6.2 — Forestry workers / 8.3.4 — Agricultural machinery operators",
    onetZone: 2,
    deficit: "zrównoważony",
    topRoles: [
      "Operator kombajnu",
      "Traktorzysta",
      "Agronom",
      "Technik rolnik",
      "Leśnik",
      "Pilarz / operator pilarki",
      "Hodowca trzody / bydła",
      "Ogrodnik",
      "Kierownik gospodarstwa rolnego",
      "Doradca rolny (ODR)",
      "Sadownik",
    ],
    coreSkills: [
      "Obsługa maszyn rolniczych (John Deere, Case IH, Claas, New Holland, Fendt)",
      "Uprawa zbóż, rzepaku, kukurydzy, buraków cukrowych",
      "Nawożenie i ochrona roślin (integrowana produkcja IP)",
      "Hodowla zwierząt (tucz, rozród, żywienie)",
      "Obsługa kombajnu zbożowego i kukurydzianego",
      "Pilarki spalinowe i elektryczne (ścinka, okrzesywanie)",
      "Prawo jazdy kat. T (ciągnik rolniczy)",
      "ARiMR / PROW / dopłaty bezpośrednie / IACS",
      "Uprawnienia chemizacyjne (stosowanie środków ochrony roślin)",
      "Dokumentacja weterynaryjna i hodowlana",
      "Nawadnianie i melioracja",
    ],
    actionVerbs: [
      "uprawiałem",
      "zbierałem",
      "hodowałem",
      "nawoziłem",
      "opryskiwałem",
      "obsługiwałem",
      "serwisowałem",
      "zarządzałem",
      "dokumentowałem",
      "pozyskiwałem",
    ],
    achievementTemplates: [
      "Prowadziłem uprawę [X] ha [zboża/rzepaku/kukurydzy], osiągając plon [X] t/ha",
      "Obsługiwałem kombajn [marka model] zbierając [X] ha/sezon w [X] godz. pracy",
      "Hodowałem stado [X] sztuk [bydła/trzody], średni przyrost [X] kg/dzień",
      "Zrealizowałem dofinansowanie ARiMR/PROW na kwotę [X] zł — modernizacja gospodarstwa [typ]",
      "Prowadziłem dokumentację IACS dla gospodarstwa [X] ha — 100% terminowość wniosków",
    ],
    certifications: [
      "Prawo jazdy kat. T (ciągnik rolniczy)",
      "Uprawnienia do stosowania środków ochrony roślin (chemizacja)",
      "Uprawnienia UDT (wózki widłowe, ładowarki teleskopowe)",
      "Kurs kombajnisty",
      "Kurs operatora pilarki spalinowej",
      "Certyfikat integrowanej produkcji (IP)",
      "Uprawnienia na opryskiwacze ciągnikowe",
      "Szkolenie rolnicze w ODR",
      "Kurs inseminatora (hodowla bydła)",
    ],
    atsKeywords: [
      "rolnictwo",
      "agronom",
      "ARiMR",
      "PROW",
      "IACS",
      "IP",
      "kombajn",
      "ciągnik",
      "John Deere",
      "Claas",
      "hodowla",
      "uprawa",
      "chemizacja",
      "ha",
      "plon",
      "zboża",
      "rzepak",
      "kukurydza",
      "trzoda",
      "bydło",
      "leśnik",
      "pilarz",
      "prawo jazdy T",
    ],
    toneHint:
      "W rolnictwie liczą się hektary, plony (t/ha), marki i modele maszyn, certyfikaty chemizacji. Rolnik = 'prowadziłem 40 ha kukurydzy, plon 11 t/ha, zrealizowałem dofinansowanie PROW 180 tys. zł'. Nie pisz 'pracowałem w gospodarstwie'.",
  },
};

// ─── Action Verbs (by category) ───────────────────────────────────────────────

export const ACTION_VERBS = {
  management: ["zarządzałem", "koordynowałem", "nadzorowałem", "delegowałem", "kierowałem", "prowadziłem", "organizowałem", "planowałem", "kontrolowałem", "motywowałem"],
  achievement: ["zwiększyłem", "zoptymalizowałem", "zredukowałem", "wdrożyłem", "osiągnąłem", "poprawiłem", "usprawnałem", "przekroczyłem", "podniosłem", "rozwinąłem"],
  creation: ["zaprojektowałem", "opracowałem", "stworzyłem", "zbudowałem", "uruchomiłem", "założyłem", "zainicjowałem", "wynalazłem", "oprogramowałem", "wykreowałem"],
  analysis: ["przeanalizowałem", "zbadałem", "zidentyfikowałem", "zmapowałem", "oszacowałem", "zdiagnozowałem", "oceniłem", "prognozowałem", "zmierzyłem", "przetestowałem"],
  communication: ["negocjowałem", "prezentowałem", "szkoliłem", "doradzałem", "reprezentowałem", "raportowałem", "konsultowałem", "mediowałem", "promowałem", "publikowałem"],
  technical: ["obsługiwałem", "montowałem", "naprawiałem", "spawałem", "produkowałem", "instalowałem", "serwisowałem", "programowałem", "kalibrowałem", "diagnozowałem"],
};

// ─── Anti-patterns (banned phrases → replacements) ────────────────────────────

export const ANTI_PATTERNS: Array<{ bad: string; replacement: string }> = [
  { bad: "odpowiedzialny za", replacement: "zarządzałem / koordynowałem / wdrożyłem [+ konkretną rzecz]" },
  { bad: "brałem udział", replacement: "współtworzyłem / realizowałem [+ co dokładnie]" },
  { bad: "praca zespołowa", replacement: "[opisz rolę w zespole: 'koordynowałem 5-osobowy zespół']" },
  { bad: "dobra komunikacja", replacement: "[konkret: 'negocjowałem warunki z 12 dostawcami' / 'prezentowałem wyniki zarządowi']" },
  { bad: "elastyczność", replacement: "[konkret: 'dostosowywałem procesy do zmian w harmonogramie']" },
  { bad: "zaangażowany", replacement: "[metryka: 'realizowałem 115% planu sprzedaży']" },
  { bad: "zmotywowany", replacement: "[dowód: 'awansowałem z X na Y w ciągu Z miesięcy']" },
  { bad: "kreatywny", replacement: "[efekt: 'zaprojektowałem kampanię, która wygenerowała X leadów']" },
  { bad: "samodzielny", replacement: "[sytuacja: 'prowadziłem projekt X od koncepcji do wdrożenia bez nadzoru']" },
  { bad: "umiejętność pracy pod presją", replacement: "[kontekst: 'obsługiwałem 200 klientów/dzień w sezonie świątecznym']" },
  { bad: "zarządzanie czasem", replacement: "[efekt: 'realizowałem X projektów jednocześnie, 100% w terminie']" },
  { bad: "znajomość komputera", replacement: "[narzędzia: 'Excel (VLOOKUP, pivot, makra), SAP, system WMS']" },
  { bad: "References available upon request", replacement: "[usuń — to angielski zwyczaj, w PL nieużywany]" },
  { bad: "Preferowana forma zatrudnienia", replacement: "[usuń — to negocjacja na rozmowie, nie do CV]" },
  { bad: "Data urodzenia:", replacement: "[usuń — RODO nie pozwala na dyskryminację wiekową, pracodawca nie ma prawa wymagać]" },
  { bad: "Stan cywilny:", replacement: "[usuń — nieistotne dla rekrutacji, dyskryminujące]" },
  { bad: "Narodowość:", replacement: "[usuń — dyskryminujące, pracodawca nie ma prawa wymagać]" },
  { bad: "PESEL:", replacement: "[usuń — PESEL NIGDY nie wpisuj w CV, to dane wrażliwe]" },
  { bad: "Liczba dzieci:", replacement: "[usuń — dyskryminujące, poza zakresem rekrutacji]" },
  { bad: "Religia:", replacement: "[usuń — niedopuszczalne w procesie rekrutacyjnym]" },
];

// ─── Helper: get industry profile for prompt ──────────────────────────────────

export function getIndustryContext(industryId: string): string {
  const profile = INDUSTRY_PROFILES[industryId];
  if (!profile) return "";

  return `
KONTEKST BRANŻY: ${profile.label}
Klasyfikacja ESCO: ${profile.escoGroup}
Status na rynku pracy (Barometr Zawodów 2025): ${profile.deficit}

Najpopularniejsze stanowiska: ${profile.topRoles.join(", ")}
Kluczowe umiejętności (ESCO + BKL PARP): ${profile.coreSkills.join(", ")}
Certyfikaty/uprawnienia (PRK/ZSK): ${profile.certifications.join(", ")}
Słowa kluczowe ATS: ${profile.atsKeywords.join(", ")}

Silne czasowniki dla tej branży: ${profile.actionVerbs.join(", ")}

Wzory osiągnięć:
${profile.achievementTemplates.map((t, i) => `${i + 1}. ${t}`).join("\n")}

Ton pisania: ${profile.toneHint}
`.trim();
}

export function getAntiPatternsPrompt(): string {
  return `
ZABRONIONE FRAZY — zamień je na konkrety:
${ANTI_PATTERNS.map((p) => `• "${p.bad}" → ${p.replacement}`).join("\n")}
`.trim();
}
